name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Cấp quyền ghi cho nội dung và pages
    permissions:
      contents: write
      pages: write

    steps:
      # Bước 1: Checkout code
      - name: Check out repository
        uses: actions/checkout@v3

      # Bước 2: Cài đặt dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./client

      # Bước 3: Build dự án
      - name: Build project
        run: npm run build
        working-directory: ./client

      # Bước 4: Deploy lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages             # Nhánh sẽ chứa build
          folder: ./client/build       # Thư mục build (sinh ra sau npm run build)
          token: ${{ secrets.GITHUB_TOKEN }}